### ISSUE TITLE
 ERROR:  unsupported Unicode escape sequence

### ISSUE THREAD

**Issue by dkocich** [dzuluaga/postgress-import-json#1]
Hello,
I get this kind of error when importing JSON.
Is there any change to have "skip row on error" option?

JSON looks like this:

{"_id":{"$oid":"56362b7701a402b4520677f7"},"contributors":null,"truncated":false,"text":"Vamos a perdernos esta noche,y nos importa una mierda lo que los demas digan, cierto? Alguien haceâ¦ https://t.co/ifojOoWRjE","is_quote_status":false,"in_reply_to_status_id":null,"id":{"$numberLong":"660836319162052612"},"favorite_count":0,"source":"\u003ca href=\"http://instagram.com\" rel=\"nofollow\"\u003eInstagram\u003c/a\u003e","retweeted":false,"coordinates":{"type":"Point","coordinates":[-3.7644,40.3281]},"entities":{"symbols":[],"user_mentions":[],"hashtags":[],"urls":[{"url":"https://t.co/ifojOoWRjE","indices":[100,123],"expanded_url":"https://instagram.com/p/9i_bE1x2YZ/","display_url":"instagram.com/p/9i_bE1x2YZ/"}]},"in_reply_to_screen_name":null,"in_reply_to_user_id":null,"retweet_count":0,"id_str":"660836319162052612","favorited":false,"user":{"follow_request_sent":null,"has_extended_profile":false,"profile_use_background_image":true,"default_profile_image":false,"id":{"$numberLong":"2288613401"},"profile_background_image_url_https":"https://abs.twimg.com/images/themes/theme1/bg.png","verified":false,"profile_text_color":"333333","profile_image_url_https":"https://pbs.twimg.com/profile_images/648478389498707968/T9YC66l1_normal.jpg","profile_sidebar_fill_color":"DDEEF6","entities":{"url":{"urls":[{"url":"http://t.co/RzpL5rEFcl","indices":[0,22],"expanded_url":"http://instagram.com/albasweet_sorrow","display_url":"instagram.com/albasweet_sorrâ¦"}]},"description":{"urls":[]}},"followers_count":286,"profile_sidebar_border_color":"C0DEED","id_str":"2288613401","profile_background_color":"C0DEED","listed_count":0,"is_translation_enabled":false,"utc_offset":null,"statuses_count":4472,"description":"Â«Lo que hoy son errores maÃ±ana serÃ¡n experienciasÂ» 'no te rindas'ã TLS'2 ,LEGANES,JAÃNã","friends_count":248,"location":"â§IV\u0000â£\u0000","profile_link_color":"0084B4","profile_image_url":"http://pbs.twimg.com/profile_images/648478389498707968/T9YC66l1_normal.jpg","following":null,"geo_enabled":true,"profile_banner_url":"https://pbs.twimg.com/profile_banners/2288613401/1441706354","profile_background_image_url":"http://abs.twimg.com/images/themes/theme1/bg.png","screen_name":"Albalaguna_","lang":"es","profile_background_tile":false,"favourites_count":694,"name":"ALBA LAGUNAâ\u0000","notifications":null,"url":"http://t.co/RzpL5rEFcl","created_at":{"$date":"2014-01-17T20:05:13.000Z"},"contributors_enabled":false,"time_zone":null,"protected":false,"default_profile":true,"is_translator":false},"geo":{"type":"Point","coordinates":[40.3281,-3.7644]},"in_reply_to_user_id_str":null,"possibly_sensitive":false,"lang":"es","created_at":{"$date":"2015-11-01T15:10:30.000Z"},"in_reply_to_status_id_str":null,"place":{"country_code":"ES","url":"https://api.twitter.com/1.1/geo/id/4a48243dbd8e054f.json","country":"EspaÃ±a","place_type":"city","bounding_box":{"type":"Polygon","coordinates":[[[-3.8183347,40.2926631],[-3.7210189,40.2926631],[-3.7210189,40.3651347],[-3.8183347,40.3651347]]]},"contained_within":[],"full_name":"LeganÃ©s, Comunidad de Madrid","attributes":{},"id":"4a48243dbd8e054f","name":"LeganÃ©s"},"metadata":{"iso_language_code":"es","result_type":"recent"}}

**Comment by dkocich** [comment]
Replacing \u0000 solved it.

**Comment by juanpaucar** [comment]
@dkocich How did you get replace that value inside the JSON?

**Comment by dkocich** [comment]
@juanpaucar There are several ways to find text pattern in your text. See [solution for large files](http://stackoverflow.com/questions/6951687/find-and-replace-text-in-a-47gb-large-file) or something like `regexp_replace(text, '\\u0000', ' ', 'g');` in DBs...
